const { EXTERNAL_PACKAGES } = require('../config/paths.js');
const { JOI_ERROR_KEYS, JOI_VALIDATION_MESSAGES, SERVICE_MESSAGES } = require('../utils/messages.utils.js');
const Joi = require(EXTERNAL_PACKAGES.JOI);

// Esquema para login
const loginSchema = Joi.object({
  email: Joi.string()
    .email()
    .required()
    .messages({
      [JOI_ERROR_KEYS.STRING_EMAIL]: JOI_VALIDATION_MESSAGES.EMAIL_INVALID,
      [JOI_ERROR_KEYS.STRING_EMPTY]: JOI_VALIDATION_MESSAGES.EMAIL_REQUIRED,
      [JOI_ERROR_KEYS.ANY_REQUIRED]: JOI_VALIDATION_MESSAGES.EMAIL_REQUIRED
    }),

  password: Joi.string()
    .min(6)
    .required()
    .messages({
      [JOI_ERROR_KEYS.STRING_MIN]: JOI_VALIDATION_MESSAGES.PASSWORD_MIN_6_CHARS,
      [JOI_ERROR_KEYS.STRING_EMPTY]: JOI_VALIDATION_MESSAGES.PASSWORD_REQUIRED,
      [JOI_ERROR_KEYS.ANY_REQUIRED]: JOI_VALIDATION_MESSAGES.PASSWORD_REQUIRED
    })
});

// Esquema para registro
const registerSchema = Joi.object({
  email: Joi.string()
    .email()
    .required()
    .messages({
      [JOI_ERROR_KEYS.STRING_EMAIL]: JOI_VALIDATION_MESSAGES.EMAIL_INVALID,
      [JOI_ERROR_KEYS.STRING_EMPTY]: JOI_VALIDATION_MESSAGES.EMAIL_REQUIRED,
      [JOI_ERROR_KEYS.ANY_REQUIRED]: JOI_VALIDATION_MESSAGES.EMAIL_REQUIRED
    }),

  password: Joi.string()
    .min(6)
    .max(50)
    .pattern(SERVICE_MESSAGES.PASSWORD_PATTERN)
    .required()
    .messages({
      [JOI_ERROR_KEYS.STRING_MIN]: JOI_VALIDATION_MESSAGES.PASSWORD_MIN_6_CHARS,
      [JOI_ERROR_KEYS.STRING_MAX]: JOI_VALIDATION_MESSAGES.PASSWORD_MAX_50_CHARS,
      [JOI_ERROR_KEYS.STRING_PATTERN_BASE]: JOI_VALIDATION_MESSAGES.PASSWORD_PATTERN_INVALID,
      [JOI_ERROR_KEYS.STRING_EMPTY]: JOI_VALIDATION_MESSAGES.PASSWORD_REQUIRED,
      [JOI_ERROR_KEYS.ANY_REQUIRED]: JOI_VALIDATION_MESSAGES.PASSWORD_REQUIRED
    }),

  confirmPassword: Joi.string()
    .valid(Joi.ref(SERVICE_MESSAGES.PASSWORD_FIELD))
    .required()
    .messages({
      [JOI_ERROR_KEYS.ANY_ONLY]: JOI_VALIDATION_MESSAGES.PASSWORDS_DO_NOT_MATCH,
      [JOI_ERROR_KEYS.STRING_EMPTY]: JOI_VALIDATION_MESSAGES.PASSWORD_CONFIRMATION_REQUIRED,
      [JOI_ERROR_KEYS.ANY_REQUIRED]: JOI_VALIDATION_MESSAGES.PASSWORD_CONFIRMATION_REQUIRED
    })
});

module.exports = {
  loginSchema,
  registerSchema
};
